### Listar el directorio raíz de una partición
GET http://54.196.151.70:8080/directory?disk=/home/jorgis/Calificacion_MIA/Discos/Disco1.mia&partition=Part11

### Listar un directorio específico dentro de una partición
GET http://54.196.151.70:8080/directory?disk=/home/jorgis/Calificacion_MIA/Discos/Disco1.mia&partition=Part11&path=/home/archivos

### Listar un directorio en una ruta más anidada
GET http://54.196.151.70:8080/directory?disk=/home/jorgis/Calificacion_MIA/Discos/Disco1.mia&partition=Part11&path=/home/archivos/user/docs

### Error: Sin especificar el disco
GET http://54.196.151.70:8080/directory?partition=Part11&path=/home/archivos

### Error: Sin especificar la partición
GET http://54.196.151.70:8080/directory?disk=/home/jorgis/Calificacion_MIA/Discos/Disco1.mia&path=/home/archivos

### Error: Disco no existente
GET http://54.196.151.70:8080/directory?disk=/ruta/inexistente/Disco1.mia&partition=Part11&path=/home/archivos

### Error: Partición no existente
GET http://54.196.151.70:8080/directory?disk=/home/jorgis/Calificacion_MIA/Discos/Disco1.mia&partition=ParticionInexistente&path=/home/archivos

### Error: Directorio no existente
GET http://54.196.151.70:8080/directory?disk=/home/jorgis/Calificacion_MIA/Discos/Disco1.mia&partition=Part11&path=/ruta/inexistente

### Intentando listar un archivo (no un directorio)
GET http://54.196.151.70:8080/directory?disk=/home/jorgis/Calificacion_MIA/Discos/Disco1.mia&partition=Part11&path=/users.txt