import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Suspense } from "react";

const inter = Inter({
  // variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased gap-16  bg-gradient-to-b from-black to-neutral-900 text-white min-h-screen`}
      >
        <Suspense fallback={<div className="text-center p-10">Cargando...</div>}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
